version: "3.8"

services:
  db:
    image: postgres:16
    container_name: laterly_postgres
    restart: always
    environment:
      POSTGRES_USER: laterly_user
      POSTGRES_PASSWORD: laterly_password
      POSTGRES_DB: laterly_db
    ports:
      - "5433:5432"
    volumes:
      - laterly_db_data:/var/lib/postgresql/data

volumes:
  laterly_db_data:
